import React, { useState } from 'react';
import { 
  FileText, 
  Sparkles, 
  CheckCircle2, 
  AlertTriangle, 
  ShieldAlert, 
  ArrowRight, 
  Copy, 
  Check, 
  Phone, 
  Mail, 
  MapPin, 
  GraduationCap, 
  Briefcase, 
  Languages, 
  MessageSquare,
  Cpu,
  BarChart3,
  Target
} from 'lucide-react';
import { ProcessedLead } from '../types/lead';

interface InputOutputComparisonProps {
  lead: ProcessedLead;
}

export const InputOutputComparison: React.FC<InputOutputComparisonProps> = ({ lead }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyOutreach = () => {
    navigator.clipboard.writeText(lead.personalizedOutreach);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const b = lead.scoreBreakdown || {
    fit: 18,
    intent: 22,
    careerReadiness: 12,
    urgency: 12,
    buyingSignal: 10,
    dataConfidence: 8,
    total: lead.priorityScore,
  };

  return (
    <div className="space-y-6">
      {/* Title & Context */}
      <div className="bg-slate-900 text-white rounded-2xl p-5 sm:p-6 shadow-sm flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="font-mono text-xs font-bold text-indigo-400 bg-indigo-950/80 border border-indigo-800/80 px-2 py-0.5 rounded">
              INPUT &rarr; OUTPUT AUDIT
            </span>
            <span className="text-xs text-slate-400">&bull;</span>
            <span className="text-xs text-slate-300 font-medium">Lead {lead.id}: {lead.name}</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-white">
            Raw CSV Ingestion vs. AI Synthesized Outputs
          </h2>
          <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
            Direct comparison showing original uncleaned candidate input from your uploaded CSV alongside the structured deterministic & AI outputs generated by the 6-stage workflow.
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <div className="bg-slate-800/80 border border-slate-700 rounded-xl px-4 py-2 text-center">
            <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Score</div>
            <div className="font-mono text-xl font-bold text-indigo-300">{lead.priorityScore}/100</div>
          </div>
          <div className="bg-slate-800/80 border border-slate-700 rounded-xl px-4 py-2 text-center">
            <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">QC Status</div>
            <div className={`font-mono text-xs font-bold ${lead.qcStatus === 'PASS' ? 'text-emerald-400' : 'text-amber-400'}`}>
              {lead.qcStatus}
            </div>
          </div>
        </div>
      </div>

      {/* Side-by-Side Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* LEFT COLUMN: RAW INPUT (5 columns) */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-white rounded-2xl border-2 border-slate-300 shadow-2xs overflow-hidden">
            {/* Header */}
            <div className="bg-slate-100/80 px-5 py-3.5 border-b border-slate-200 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-slate-600" />
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-800">
                  Raw CSV Ingestion (Input)
                </h3>
              </div>
              <span className="text-[10px] font-mono bg-slate-200 text-slate-700 px-2 py-0.5 rounded font-semibold">
                Original Record
              </span>
            </div>

            {/* Content Fields */}
            <div className="p-5 space-y-4 text-xs">
              {/* Core Identifiers */}
              <div className="space-y-2">
                <div className="flex justify-between items-start py-1 border-b border-slate-100">
                  <span className="text-slate-500 font-medium">Lead ID:</span>
                  <span className="font-mono font-bold text-slate-800">{lead.id}</span>
                </div>
                <div className="flex justify-between items-start py-1 border-b border-slate-100">
                  <span className="text-slate-500 font-medium">Full Name:</span>
                  <span className="font-bold text-slate-900">{lead.name}</span>
                </div>
                <div className="flex justify-between items-start py-1 border-b border-slate-100">
                  <span className="text-slate-500 font-medium">Phone (Raw):</span>
                  <span className="font-mono text-slate-800">{lead.phone || <em className="text-slate-400">Empty</em>}</span>
                </div>
                <div className="flex justify-between items-start py-1 border-b border-slate-100">
                  <span className="text-slate-500 font-medium">Email (Raw):</span>
                  <span className="text-slate-800">{lead.email || <em className="text-slate-400">Empty</em>}</span>
                </div>
                <div className="flex justify-between items-start py-1 border-b border-slate-100">
                  <span className="text-slate-500 font-medium">Location:</span>
                  <span className="text-slate-800">{lead.location || <em className="text-slate-400">Not stated</em>}</span>
                </div>
              </div>

              {/* Qualifications */}
              <div className="space-y-2 pt-2">
                <div className="text-[11px] font-bold uppercase tracking-wider text-slate-600">
                  Candidate Stated Credentials
                </div>

                <div className="bg-slate-50 rounded-xl p-3 border border-slate-200/80 space-y-2">
                  <div className="flex items-center gap-2">
                    <GraduationCap className="w-3.5 h-3.5 text-slate-500" />
                    <span className="text-slate-500">Education:</span>
                    <span className="font-semibold text-slate-900 ml-auto">
                      {lead.education || <span className="text-amber-600 font-bold">Missing</span>}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <Briefcase className="w-3.5 h-3.5 text-slate-500" />
                    <span className="text-slate-500">Experience:</span>
                    <span className="font-semibold text-slate-900 ml-auto">
                      {lead.experience || <span className="text-slate-400">Not provided</span>}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <Languages className="w-3.5 h-3.5 text-slate-500" />
                    <span className="text-slate-500">German Level:</span>
                    <span className="ml-auto font-mono">
                      {lead.germanLevel ? (
                        <span className="font-bold bg-white px-2 py-0.5 rounded border border-slate-300 text-slate-800">
                          {lead.germanLevel}
                        </span>
                      ) : (
                        <span className="font-bold text-amber-600 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">
                          Missing in CSV
                        </span>
                      )}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="text-slate-500">Lead Source:</span>
                    <span className="font-medium text-slate-800 ml-auto">{lead.leadSource || 'Web Form'}</span>
                  </div>
                </div>
              </div>

              {/* Raw Inbound Notes */}
              <div className="pt-2">
                <div className="text-[11px] font-bold uppercase tracking-wider text-slate-600 mb-1.5 flex items-center justify-between">
                  <span>Raw Inbound Conversation Notes:</span>
                  <span className="text-[10px] text-slate-400">Unedited</span>
                </div>
                <div className="bg-slate-50 font-mono text-[11px] text-slate-800 p-3 rounded-xl border border-slate-200 leading-relaxed max-h-48 overflow-y-auto">
                  "{lead.conversation || 'No raw notes recorded.'}"
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: AI SYNTHESIZED OUTPUTS (7 columns) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-white rounded-2xl border-2 border-indigo-200/90 shadow-2xs overflow-hidden">
            {/* Header */}
            <div className="bg-linear-to-r from-indigo-50 via-white to-indigo-50/50 px-5 py-3.5 border-b border-indigo-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-indigo-600" />
                <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-950">
                  AI Pipeline Synthesized Outputs
                </h3>
              </div>
              <span className="text-[10px] font-mono bg-indigo-100 text-indigo-800 px-2 py-0.5 rounded font-bold">
                6 Components Executed
              </span>
            </div>

            <div className="p-5 space-y-5 text-xs">
              {/* Output Component 1: Data Cleaning Engine */}
              <div className="rounded-xl border border-slate-200 p-3.5 bg-slate-50/50 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                    1. Data Cleaning Engine Output
                  </span>
                  <span className="text-[10px] font-mono text-emerald-700 font-bold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                    CLEANED
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-2 text-[11px]">
                  <div className="bg-white p-2 rounded-lg border border-slate-200">
                    <span className="text-slate-400 block text-[10px]">Phone Normalization:</span>
                    <span className="font-mono font-medium text-slate-800">
                      {lead.phone ? `✓ Standardized ${lead.phone}` : '⚠ Missing'}
                    </span>
                  </div>

                  <div className="bg-white p-2 rounded-lg border border-slate-200">
                    <span className="text-slate-400 block text-[10px]">Duplicate Check:</span>
                    <span className="font-medium text-slate-800">
                      {lead.duplicateStatus === 'Confirmed Duplicate' ? (
                        <span className="text-rose-600 font-bold">⚠ Confirmed Duplicate</span>
                      ) : (
                        <span className="text-emerald-700 font-bold">✓ Unique Candidate</span>
                      )}
                    </span>
                  </div>
                </div>
              </div>

              {/* Output Component 2: AI Classification Agent */}
              <div className="rounded-xl border border-indigo-100 p-3.5 bg-indigo-50/20 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-950 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-indigo-600"></span>
                    2. AI Classification Agent Output
                  </span>
                  <span className="text-[10px] font-mono font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded border border-indigo-200">
                    Confidence: {lead.confidence}%
                  </span>
                </div>

                <div className="bg-white p-3 rounded-lg border border-indigo-100 space-y-1.5">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-500">Relevant:</span>
                    <span className={`font-bold px-2 py-0.5 rounded text-[11px] ${
                      lead.relevant === 'YES' ? 'bg-emerald-100 text-emerald-800' : lead.relevant === 'REVIEW' ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-800'
                    }`}>
                      {lead.relevant}
                    </span>
                  </div>

                  <p className="text-slate-800 font-medium">
                    {lead.relevanceReason}
                  </p>

                  {lead.evidence && lead.evidence.length > 0 && (
                    <div className="pt-1">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-0.5">
                        Extracted Evidence:
                      </span>
                      <ul className="space-y-0.5 pl-1">
                        {lead.evidence.map((ev, i) => (
                          <li key={i} className="text-slate-700 flex items-center gap-1">
                            <span className="text-indigo-500">&bull;</span>
                            <span>{ev}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </div>

              {/* Output Component 3: AI Lead Enrichment Agent */}
              <div className="rounded-xl border border-slate-200 p-3.5 bg-slate-50/50 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-indigo-600"></span>
                    3. AI Enrichment Agent Output
                  </span>
                  <span className="text-[10px] font-mono text-slate-600 bg-white px-2 py-0.5 rounded border border-slate-200 font-semibold">
                    Profile & Intent
                  </span>
                </div>

                <div className="bg-white p-3 rounded-lg border border-slate-200/80 space-y-2">
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Synthesized Profile:</span>
                    <p className="text-slate-900 font-medium">{lead.profile}</p>
                  </div>

                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Detected Intent:</span>
                    <p className="text-slate-800 italic">"{lead.intent}"</p>
                  </div>

                  {lead.potentialNeeds && lead.potentialNeeds.length > 0 && (
                    <div>
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-0.5">Potential Needs:</span>
                      <div className="flex flex-wrap gap-1">
                        {lead.potentialNeeds.map((need, i) => (
                          <span key={i} className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded text-[11px] border border-slate-200">
                            {need}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Output Component 4: Prioritization Engine */}
              <div className="rounded-xl border border-slate-200 p-3.5 bg-slate-50/50 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-indigo-600"></span>
                    4. Deterministic Prioritization Matrix Output
                  </span>
                  <span className="text-[10px] font-mono font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded border border-indigo-200">
                    {lead.priorityScore}/100 &bull; {lead.priority}
                  </span>
                </div>

                <div className="bg-white p-3 rounded-lg border border-slate-200/80">
                  <div className="grid grid-cols-3 gap-2 text-center text-[10px] font-mono">
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Fit</div>
                      <div className="font-bold text-slate-800">{b.fit}/20</div>
                    </div>
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Intent</div>
                      <div className="font-bold text-slate-800">{b.intent}/25</div>
                    </div>
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Career</div>
                      <div className="font-bold text-slate-800">{b.careerReadiness}/15</div>
                    </div>
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Urgency</div>
                      <div className="font-bold text-slate-800">{b.urgency}/15</div>
                    </div>
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Signal</div>
                      <div className="font-bold text-slate-800">{b.buyingSignal}/15</div>
                    </div>
                    <div className="bg-slate-50 p-1.5 rounded border border-slate-100">
                      <div className="text-slate-400">Confidence</div>
                      <div className="font-bold text-slate-800">{b.dataConfidence}/10</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Output Component 5: Outreach Agent */}
              <div className="rounded-xl border border-indigo-100 p-3.5 bg-indigo-50/20 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-950 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-indigo-600"></span>
                    5. Personalized Outreach Agent Output
                  </span>

                  <button
                    onClick={handleCopyOutreach}
                    className="inline-flex items-center gap-1 text-[11px] font-semibold text-indigo-700 bg-white border border-indigo-200 px-2 py-0.5 rounded hover:bg-indigo-50 transition cursor-pointer"
                  >
                    {copied ? (
                      <>
                        <Check className="w-3 h-3 text-emerald-600" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3 text-slate-400" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>

                <div className="bg-white p-3 rounded-lg border border-indigo-100 space-y-1.5">
                  <div className="text-[11px] font-bold text-slate-900">
                    Action: <span className="font-semibold text-indigo-900">{lead.recommendedNextAction}</span>
                  </div>
                  <p className="text-slate-800 italic leading-relaxed bg-slate-50 p-2.5 rounded border border-slate-200/60">
                    "{lead.personalizedOutreach}"
                  </p>
                </div>
              </div>

              {/* Output Component 6: Reviewer / Quality Control Agent */}
              <div className={`rounded-xl border p-3.5 space-y-2 ${
                lead.qcStatus === 'PASS'
                  ? 'border-emerald-200 bg-emerald-50/30'
                  : 'border-amber-300 bg-amber-50/40'
              }`}>
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-800 flex items-center gap-1.5">
                    <span className={`w-2 h-2 rounded-full ${lead.qcStatus === 'PASS' ? 'bg-emerald-500' : 'bg-amber-500'}`}></span>
                    6. Reviewer / QC Guardrail Agent Output
                  </span>

                  <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${
                    lead.qcStatus === 'PASS'
                      ? 'bg-emerald-100 text-emerald-800 border-emerald-300'
                      : 'bg-amber-100 text-amber-900 border-amber-300'
                  }`}>
                    {lead.qcStatus === 'PASS' ? '✓ PASS' : '⚠ REVIEW'}
                  </span>
                </div>

                <div className="bg-white p-3 rounded-lg border border-slate-200/80 space-y-1">
                  <p className="text-slate-800">
                    {lead.qcReason}
                  </p>
                  {lead.qcReport?.recommendedFix && (
                    <p className="text-amber-900 font-medium text-[11px] pt-1 border-t border-slate-100">
                      <strong>Guardrail Recommendation:</strong> {lead.qcReport.recommendedFix}
                    </p>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
